const mongoose = require('mongoose');
const Lender = require('../models/Lender');
require('dotenv').config();

const lenders = [
  {
    slug: 'tala',
    name: 'Tala Mobile Loan',
    shortName: 'Tala Mobile',
    category: 'Fintech Mobile app',
    interestRate: 15,
    feeAmount: 10000,
    repaymentPeriodDays: 30,
    trustScore: 4.5,
    badge: 'Fast disbursement',
    color: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    license: 'UMRA Registered',
    licenseColor: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    loanRange: 'UGX 50,000 - 1,000,000',
    description: 'Fast automated credit scoring via mobile app logs. No collateral required.',
    privacyNote: 'Collects contacts list and device info for identity checks.',
    safetyStatus: 'Safe (Regulated)',
  },
  {
    slug: 'branch',
    name: 'Branch Finance',
    shortName: 'Branch',
    category: 'Fintech Mobile app',
    interestRate: 12,
    feeAmount: 15000,
    repaymentPeriodDays: 30,
    trustScore: 4.6,
    badge: 'Lower Mobile Rate',
    color: 'text-emerald-400 border-emerald-600/50 bg-emerald-950/40',
    license: 'UMRA Registered',
    licenseColor: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    loanRange: 'UGX 80,000 - 2,000,000',
    description: 'Low-cost mobile digital credit. Direct mobile money transfer within minutes.',
    privacyNote: 'Accesses GPS data and device identifiers for credit score computations.',
    safetyStatus: 'Safe (Regulated)',
  },
  {
    slug: 'mkopa',
    name: 'M-Kopa Cash',
    shortName: 'M-Kopa Cash',
    category: 'Asset Financer',
    interestRate: 25,
    feeAmount: 30000,
    repaymentPeriodDays: 60,
    trustScore: 3.8,
    badge: 'High Cost / Flexible',
    color: 'text-amber-400 border-amber-600/50 bg-amber-950/40',
    license: 'Consumer Goods Provider',
    licenseColor: 'text-amber-400 border-amber-600/50 bg-amber-950/40',
    loanRange: 'UGX 200,000 - 1,500,000',
    description: 'Asset finance solutions linked to phone locking and solar power lease systems.',
    privacyNote: 'Remote lock features installed on financed smartphones.',
    safetyStatus: 'Caution (Device Locks)',
  },
  {
    slug: 'watu',
    name: 'Watu Credit Uganda',
    shortName: 'Watu Credit',
    category: 'Microfinance Institution',
    interestRate: 20,
    feeAmount: 50000,
    repaymentPeriodDays: 90,
    trustScore: 3.9,
    badge: 'Longer repayment',
    color: 'text-amber-400 border-amber-600/50 bg-amber-950/40',
    license: 'Tier 4 Microfinance',
    licenseColor: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    loanRange: 'UGX 500,000 - 5,000,000',
    description: 'Primarily specializes in asset leasing (Boda Boda financing) and micro business loans.',
    privacyNote: 'GPS trackers installed on financed assets; weekly repayments required.',
    safetyStatus: 'Safe (Asset Collateral)',
  },
  {
    slug: 'ugtrust',
    name: 'Uganda Trust Microfinance',
    shortName: 'Uganda Trust',
    category: 'Microfinance Institution',
    interestRate: 8,
    feeAmount: 20000,
    repaymentPeriodDays: 90,
    trustScore: 4.8,
    badge: 'Highly Regulated',
    color: 'text-emerald-400 border-emerald-600/50 bg-emerald-950/40',
    license: 'BOU Regulated (MDI)',
    licenseColor: 'text-emerald-400 border-emerald-600/50 bg-emerald-950/40',
    loanRange: 'UGX 1,000,000 - 20,000,000',
    description: 'Traditional savings and loan microfinance deposit-taking institution regulated by Bank of Uganda.',
    privacyNote: 'Requires standard physical verification, guarantor forms, and local bank statement logs.',
    safetyStatus: 'Highly Secure (Regulated)',
  },
  {
    slug: 'platinum',
    name: 'Platinum Credit Uganda',
    shortName: 'Platinum Credit',
    category: 'Microfinance Institution',
    interestRate: 18,
    feeAmount: 40000,
    repaymentPeriodDays: 120,
    trustScore: 4.1,
    badge: 'UMRA Registered',
    color: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    license: 'UMRA Registered',
    licenseColor: 'text-teal-400 border-teal-600/50 bg-teal-950/40',
    loanRange: 'UGX 300,000 - 8,000,000',
    description: 'Provides quick civil servant logbook and salary loans. High limits with quick turnarounds.',
    privacyNote: 'Salary deduction agreements or logbook title transfers required.',
    safetyStatus: 'Safe (Contractual)',
  },
  {
    slug: 'tugende',
    name: 'Tugende Lease Finance',
    shortName: 'Tugende Lease',
    category: 'Asset Financer',
    interestRate: 22,
    feeAmount: 60000,
    repaymentPeriodDays: 180,
    trustScore: 4.0,
    badge: 'Asset Lease Option',
    color: 'text-amber-400 border-amber-600/50 bg-amber-950/40',
    license: 'Asset Lease Licenced',
    licenseColor: 'text-amber-400 border-amber-600/50 bg-amber-950/40',
    loanRange: 'UGX 800,000 - 6,000,000',
    description: 'Ownership path lease financing for boda motorcycles, engines, and agricultural gear.',
    privacyNote: 'Asset tracking enabled. Mandatory insurance packages bundled into weekly fees.',
    safetyStatus: 'Safe (Lease Option)',
  },
  {
    slug: 'zuricash',
    name: 'Zuri Cash Mobile',
    shortName: 'Zuri Cash',
    category: 'Fintech Mobile app',
    interestRate: 28,
    feeAmount: 35000,
    repaymentPeriodDays: 14,
    trustScore: 3.2,
    badge: 'Unregulated Web',
    color: 'text-rose-400 border-rose-600/50 bg-rose-950/40',
    license: 'Unregulated Web Platform',
    licenseColor: 'text-rose-400 border-rose-600/50 bg-rose-950/40',
    loanRange: 'UGX 30,000 - 300,000',
    description: 'Short-term high interest mobile credit app. Quick payouts but aggressive penalties.',
    privacyNote: 'Aggressive data scraping; contacts and photo galleries are uploaded to external databases.',
    safetyStatus: 'High Risk (Predatory Warnings)',
  },
];

const seedLenders = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Lender.deleteMany({});
    await Lender.insertMany(lenders);
    console.log(`Seeded ${lenders.length} lenders`);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedLenders();
